en:
  - as
  - ast
  - ay
  - ba
  - ckb
  - ha
  - ig
  - ilo
  - is
  - kg
  - ln
  - lg
  - nso
  - oc
  - om
  - ss
  - tn
  - ts
  - wo
  - yue
  - zh
  - zu
ca:
  - oc
es:
  - as
  - ast
  - ay
  - ba
  - ckb
  - ha
  - ig
  - ilo
  - is
  - kg
  - ln
  - lg
  - nso
  - oc
  - om
  - ss
  - ti
  - tn
  - ts
  - yue
  - zh
  - zu
fr:
  - as
  - ast
  - ay
  - ba
  - ckb
  - ha
  - ig
  - ilo
  - is
  - kg
  - ln
  - lg
  - nso
  - oc
  - om
  - ss
  - ti
  - tn
  - ts
  - wo
  - yue
  - zh
  - zu
pt:
  - oc
ru:
  - ba
zh:
  - yue
