en:
  - zh
  - wuu
es:
  - zh
  - wuu
fr:
  - zh
  - wuu
ja:
  - zh
  - wuu
ko:
  - zh
  - wuu
pt:
  - zh
  - wuu
ru:
  - zh
  - wuu
simple:
  - zh
  - wuu
zh:
  - es
  - fr
  - ja
  - ko
  - pt
  - ru
  - simple
  - wuu
